# Custom Language File for Launcher Customizer

[ejs.app]
title = "Island Launcher"

[ejs.landing]
mediaHomeURL = "https://youtu.be/dQw4w9WgXcQ?si=lnImWfufnhCW0eFT"
mediaLinkURL = "#"
mediaMapURL = "#"
mediaGitHubURL = "https://github.com/ycarrot1/BermudaLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/QGcB4Tfejy"

[ejs.settings]
sourceGithubLink = "https://github.com/ycarrot1/BermudaLauncher"
supportLink = "https://github.com/ycarrot1/BermudaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Island Launcher"
welcomeDescription = "아일랜드 서버를 플레이 해주셔서 감사합니다."
welcomeDescCTA = "버그나 문제점이 발생한 경우 디스코드 서버를 방문해주세요."
